spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bytedance_bigdata?serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      file-size-threshold: 0
      # location: E:/tmp/
      # enabled: true
  thymeleaf:
    cache: false
  redis:
    database: 11
    host: localhost
    port: 6379
#  http:
#    multipart:
#      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cq.entity
  configuration:
    useGeneratedKeys: true
    mapUnderscoreToCamelCase: true